# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BpP8M7cJrhKxM5hsR1O_SQmLZ8W3A335
"""

import cv2
import numpy as np
import datetime
from keras.models import load_model
from tensorflow import keras
from django.shortcuts import render, redirect


def mask_detect(source):
    model = keras.models.load_model('model-017.model')
    # model = load_model('face_mask_model.h5')
    face_clsfr = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    source = cv2.VideoCapture(0)
    labels_dict = {0: 'MASK', 1: ' ENTRY PROHIBITED'}
    color_dict = {0: (0, 255, 0), 1: (0, 0, 255)}
    while (True):
        dt = str(datetime.datetime.now())
        ret, img = source.read()
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_clsfr.detectMultiScale(gray, 1.3, 5)
        for x, y, w, h in faces:
            data_name = []
            face_img = gray[y:y + w, x:x + w]
            resized = cv2.resize(face_img, (100, 100))
            normalized = resized / 255.0
            reshaped = np.reshape(normalized, (1, 100, 100, 1))
            result = model.predict(reshaped)

            label = np.argmax(result, axis=1)[0]

            data_name.append(labels_dict[label])

            cv2.rectangle(img, (x, y), (x + w, y + h), color_dict[label], 2)
            cv2.rectangle(img, (x, y - 40), (x + w, y), color_dict[label], -1)
            cv2.putText(img, dt, (10, 450), cv2.FONT_HERSHEY_SIMPLEX, 1, (210, 155, 155), 4, cv2.LINE_8)
            cv2.putText(img, labels_dict[label], (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (128, 0, 128), 2)
        cv2.imshow('LIVE', img)
        # print(label)
        if cv2.waitKey(1) == ord("a"):
            # if (key == 27):
            break

    cv2.destroyAllWindows()
    source.release()

    return redirect('user_home')
